"""Exact parameter-shift gradient of the WP(theta,0)=exp(i*theta*Z) gate
family, for both the weight-1 (`photonic_iqp_distribution`) and weight-2
(`photonic_weight2_iqp_distribution`) circuit families defined in
iqp_photonic_encoding.py.

This is TRAIN-01's foundational gradient primitive: "exact parameter-shift
on the existing distribution functions... NOT MerLin QuantumLayer autograd"
(MerLin's QuantumLayer categorically rejects this project's polarization-
annotated BasicStates -- confirmed live during v3.0 research, see STATE.md).

Shift rule (17-RESEARCH.md Pattern 1, derived and numerically verified
there against expected_single_qubit_probs' closed form):

    d(prob_x)/d(theta_k) = prob_x(theta + pi/4 * e_k) - prob_x(theta - pi/4 * e_k)

exact, no division, no 1/2 factor. This repo's WP(theta,0) gate is
generated by Z (eigenvalues +-1), so every output probability is a
sinusoid of frequency 2 in theta_k: f(theta) = A*cos(2*theta+phi) + C, and
f(theta+s) - f(theta-s) = f'(theta) * sin(2*s). Choosing s=pi/4 makes
sin(2*s)=1, giving the exact (undivided) two-point difference above.

CRITICAL PITFALL THIS MODULE CLOSES OFF: the textbook "shift=pi/2,
divide-by-2" rule is for the DIFFERENT convention exp(-i*theta*G/2) (e.g.
Qiskit/PennyLane RZ), which has eigenvalue gap 1, not 2. Applying s=pi/2
to THIS repo's exp(i*theta*Z) convention lands on sin(2*pi/2)=sin(pi)=0 --
a silent all-zero "gradient" that looks like a legitimate barren-plateau
signal but is actually a shift-rule bug (see
tests/test_param_shift.py::TestPiOverTwoShiftPitfallRegression, which
demonstrates this directly). Accordingly, neither function below accepts a
caller-supplied shift value -- SHIFT is hardcoded to pi/4, making the
wrong-shift footgun structurally impossible via this module's public API.

Weight-2 note: photonic_weight2_iqp_distribution internally folds an
ADDITIVE constant (pi/4, per the CZ/ZZ operator identity) onto
thetas[i]/thetas[j] to realize the Z_i*Z_j interaction. An additive
constant shifts a sinusoid's phase offset (phi above), not its frequency,
so the same shift=pi/4 rule remains exact for every thetas[k] passed to
weight2_param_shift_delta (17-RESEARCH.md Pattern 1, final paragraph).
Weight-2's distribution has no simple closed form to hand, so this is
cross-validated in tests against an independent central finite-difference
rather than repeating Pattern 1's exact algebra.
"""

import sys
import os

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from iqp_photonic_encoding import (
    photonic_iqp_distribution,
    photonic_weight2_iqp_distribution,
)

SHIFT = np.pi / 4


def weight1_param_shift_delta(n, thetas, k):
    """Exact parameter-shift delta of photonic_iqp_distribution(n, thetas)
    with respect to thetas[k].

    Returns (delta, residual):
      delta: {bitstring: prob_plus - prob_minus} over the union of both
        shifted distributions' bitstring keys, missing keys defaulting to
        0.0 on either side.
      residual: max(residual_plus, residual_minus) -- a diagnostic upper
        bound on out-of-subspace leakage at the shifted parameter values
        (should be ~0 for this repo's ideal weight-1 circuit, per
        photonic_iqp_distribution's own docstring; this function does not
        assert on it, only surfaces it for the caller to check).

    Never mutates the caller's thetas list (matches this repo's own
    established convention in iqp_photonic_encoding.py).
    """
    thetas_plus = list(thetas)
    thetas_plus[k] += SHIFT
    thetas_minus = list(thetas)
    thetas_minus[k] -= SHIFT

    dist_plus, residual_plus = photonic_iqp_distribution(n, thetas_plus)
    dist_minus, residual_minus = photonic_iqp_distribution(n, thetas_minus)

    keys = set(dist_plus) | set(dist_minus)
    delta = {x: dist_plus.get(x, 0.0) - dist_minus.get(x, 0.0) for x in keys}
    return delta, max(residual_plus, residual_minus)


def weight2_param_shift_delta(n, i, j, thetas, k):
    """Exact parameter-shift delta of
    photonic_weight2_iqp_distribution(n, i, j, thetas) with respect to
    thetas[k] (k may be i, j, or any other tracked weight-1 index -- the
    additive pi/4 fold on thetas[i]/thetas[j] only shifts phase offset, not
    frequency, per this module's docstring).

    Returns (delta, residual, herald_failure_prob):
      delta: {bitstring: prob_plus - prob_minus}, union-of-keys-with-0-
        default convention, same as weight1_param_shift_delta.
      residual: max(residual_plus, residual_minus) diagnostic.
      herald_failure_prob: max(herald_fail_plus, herald_fail_minus)
        diagnostic -- surfaced separately, never merged into residual, per
        this repo's established reporting convention
        (photonic_weight2_iqp_distribution's own docstring).

    Never mutates the caller's thetas list.
    """
    thetas_plus = list(thetas)
    thetas_plus[k] += SHIFT
    thetas_minus = list(thetas)
    thetas_minus[k] -= SHIFT

    dist_plus, residual_plus, herald_fail_plus = photonic_weight2_iqp_distribution(
        n, i, j, thetas_plus
    )
    dist_minus, residual_minus, herald_fail_minus = photonic_weight2_iqp_distribution(
        n, i, j, thetas_minus
    )

    keys = set(dist_plus) | set(dist_minus)
    delta = {x: dist_plus.get(x, 0.0) - dist_minus.get(x, 0.0) for x in keys}
    return (
        delta,
        max(residual_plus, residual_minus),
        max(herald_fail_plus, herald_fail_minus),
    )
